server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_NAME:hmdp}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}
  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      database: ${REDIS_DB:0}
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: info